version: "3.7"

services:
  db:
    image: cassandra
    container_name: go-db
    ports: 
      - "9042:9042"
    restart: always
    volumes: 
      - cassandra-data:/var/lib/cassandra/data
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10

volumes:
  cassandra-data:
    external: true
