version: "3.7"

services:
  db:
    image: postgres
    container_name: ljs-postgres
    # restart: always
    restart: unless-stopped
    environment:
      - POSTGRES_DB=admin
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_PORT=5432
    # env_file:
    #   - postgres.env
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pg-data:
    external: true
  
